// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Add(arg1:storage.DriverGroup):Promise<void>;

export function All():Promise<Array<storage.DriverGroup>>;

export function Clone(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<storage.DriverGroup>;

export function MoveBehind(arg1:number,arg2:number):Promise<void>;

export function Remove(arg1:number):Promise<void>;

export function Update(arg1:storage.DriverGroup):Promise<void>;
