// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['storage']['MatchRuleStorage']['Add'](arg1);
}

export function All() {
  return window['go']['storage']['MatchRuleStorage']['All']();
}

export function Get(arg1) {
  return window['go']['storage']['MatchRuleStorage']['Get'](arg1);
}

export function RegisterEventHandlers() {
  return window['go']['storage']['MatchRuleStorage']['RegisterEventHandlers']();
}

export function Remove(arg1) {
  return window['go']['storage']['MatchRuleStorage']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['storage']['MatchRuleStorage']['Update'](arg1);
}
