// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Add(arg1:storage.RuleSet):Promise<string>;

export function All():Promise<Array<storage.RuleSet>>;

export function Get(arg1:string):Promise<storage.RuleSet>;

export function RegisterEventHandlers():Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function Update(arg1:storage.RuleSet):Promise<storage.RuleSet>;
