// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['storage']['RuleSetStorage']['Add'](arg1);
}

export function All() {
  return window['go']['storage']['RuleSetStorage']['All']();
}

export function Clone(arg1) {
  return window['go']['storage']['RuleSetStorage']['Clone'](arg1);
}

export function Get(arg1) {
  return window['go']['storage']['RuleSetStorage']['Get'](arg1);
}

export function Remove(arg1) {
  return window['go']['storage']['RuleSetStorage']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['storage']['RuleSetStorage']['Update'](arg1);
}
