// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function Add(arg1:storage.RuleSet):Promise<void>;

export function All():Promise<Array<storage.RuleSet>>;

export function Clone(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<storage.RuleSet>;

export function Remove(arg1:number):Promise<void>;

export function Update(arg1:storage.RuleSet):Promise<void>;
