/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app-info': RouteRecordInfo<
      '/app-info',
      '/app-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drivers/': RouteRecordInfo<
      '/drivers/',
      '/drivers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drivers/create': RouteRecordInfo<
      '/drivers/create',
      '/drivers/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/drivers/edit/[id]': RouteRecordInfo<
      '/drivers/edit/[id]',
      '/drivers/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/match-rules/': RouteRecordInfo<
      '/match-rules/',
      '/match-rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/match-rules/create': RouteRecordInfo<
      '/match-rules/create',
      '/match-rules/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/match-rules/edit/[id]': RouteRecordInfo<
      '/match-rules/edit/[id]',
      '/match-rules/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/porter': RouteRecordInfo<
      '/porter',
      '/porter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/app-info.vue': {
      routes:
        | '/app-info'
      views:
        | never
    }
    'src/pages/drivers/index.vue': {
      routes:
        | '/drivers/'
      views:
        | never
    }
    'src/pages/drivers/create.vue': {
      routes:
        | '/drivers/create'
      views:
        | never
    }
    'src/pages/drivers/edit/[id].vue': {
      routes:
        | '/drivers/edit/[id]'
      views:
        | never
    }
    'src/pages/match-rules/index.vue': {
      routes:
        | '/match-rules/'
      views:
        | never
    }
    'src/pages/match-rules/create.vue': {
      routes:
        | '/match-rules/create'
      views:
        | never
    }
    'src/pages/match-rules/edit/[id].vue': {
      routes:
        | '/match-rules/edit/[id]'
      views:
        | never
    }
    'src/pages/porter.vue': {
      routes:
        | '/porter'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
