// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';

export function CheckAndApplyUpdates():Promise<void>;

export function CheckForUpdates(arg1:boolean,arg2:boolean):Promise<update.UpdateCheckResult>;

export function TriggerNativeUpdate(arg1:string):Promise<void>;
