// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {porter} from '../models';
import {status} from '../models';

export function Abort():Promise<void>;

export function DownloadAndValidate(arg1:string):Promise<porter.ImportPreview>;

export function Export(arg1:string):Promise<void>;

export function ImportFromFile(arg1:string,arg2:porter.ImportOptions):Promise<void>;

export function ImportFromURL(arg1:porter.ImportOptions):Promise<void>;

export function Progress():Promise<porter.JobSnapshot>;

export function RecoverOrphanedBackups():Promise<void>;

export function Status():Promise<status.Status>;

export function ValidateZip(arg1:string):Promise<porter.ImportPreview>;
