// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function All():Promise<store.AppSetting>;

export function Update(arg1:store.AppSetting):Promise<void>;
