// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function All() {
  return window['go']['store']['AppSettingStore']['All']();
}

export function Update(arg1) {
  return window['go']['store']['AppSettingStore']['Update'](arg1);
}
