// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['store']['DriverGroupStore']['Add'](arg1);
}

export function All() {
  return window['go']['store']['DriverGroupStore']['All']();
}

export function Get(arg1) {
  return window['go']['store']['DriverGroupStore']['Get'](arg1);
}

export function IndexOf(arg1) {
  return window['go']['store']['DriverGroupStore']['IndexOf'](arg1);
}

export function MoveBehind(arg1, arg2) {
  return window['go']['store']['DriverGroupStore']['MoveBehind'](arg1, arg2);
}

export function Remove(arg1) {
  return window['go']['store']['DriverGroupStore']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['store']['DriverGroupStore']['Update'](arg1);
}
